name: youtube_downloader_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^0.13.1+1
  flutter_hooks: ^0.16.0
  youtube_explode_dart: ^1.9.1
  stream_transform: ^2.0.0
  path_provider: ^2.0.1
  path: ^1.8.0
  shared_preferences: ^2.0.5
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  cupertino_icons: ^1.0.2
  win32: ^2.0.5
  filepicker_windows: ^2.0.0
  file_picker: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  json_annotation: ^4.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  lint: ^1.5.3


flutter:
  uses-material-design: true
