# This is a basic workflow to help you get started with Actions

name: Flutter Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checout
      uses: actions/checkout@v2
    
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      
    - name: Enable desktop support	
      run: flutter config --enable-windows-desktop
      
    - name: Doctor
      run: flutter doctor -v
      
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build windows
      run: flutter build windows
    
    - name: Build apk
      run: flutter build apk
      
    - name: Upload apk artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Youtube Downloader.apk
        path: ./build/app/outputs/flutter-apk/app-release.apk
      
    - name: Install zip
      uses: TonyBogdanov/zip@1.0
      
    - name: Zip release
      run: zip -qq -r release.zip build/windows/runner/release/

    - name: Upload windows zip artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Youtube Downloader - Windows.zip
        path: release.zip
    
    
